### ISSUE TITLE
Wrong type of speech marks used in ReleationList.js

### ISSUE THREAD

**Issue by graham73may** [CondeNastDigital/cnBolt-Extensions-RelationList#10]
https://github.com/CondeNastDigital/cnBolt-Extensions-RelationList/blob/master/web/js/RelationList.js#L103

`”_blank\”`

Should be:
```
+ "<a target=\"_blank\" href=\""+self.config.boltUrl+"editcontent/##id##\">"+self.BaseEntryTemplate+"</a>"
```

Causes some funky html output.

**Comment by ToBe998** [comment]
Ah, some mystic editor seems to have supplied some special characters instead of the usual doublequotes. -.-

**Comment by ToBe998** [comment]
is on dev-master, will be released soon after some testing
