### ISSUE TITLE
Image error shown if the result doesn't have an image available

### ISSUE THREAD

**Issue by graham73may** [CondeNastDigital/cnBolt-Extensions-RelationList#11]
I'm working on quite an image-light website, images are used quite rarely which results in:

![image](https://cloud.githubusercontent.com/assets/6642498/20976389/433e9950-bc9a-11e6-9666-4e4b4989a44e.png)

Wondering what the best approach would be for this?

**Comment by ToBe998** [comment]
If i remember correctly, it currently uses Bolt's Content->getImage() method. We could (and probably should) check if an image is found and just omit the img tag if not.

**Comment by graham73may** [comment]
That would be grand! I tried to decipher the goings on in RelationList.js but it got a bit deep very quickly.

**Comment by ToBe998** [comment]
I added your css fix. The more thorough refactoring of the templating is postponed. We would want to change a couple of other things along the way ... then.

**Comment by ToBe998** [comment]
2.0.10
